language: node_js
node_js:
  - "0.10"
  - "0.11"
os:
  - linux
  - osx
before_script:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install mongodb-org
  - sudo echo 'journal = true' >> /etc/mongodb.conf
  - sudo /etc/init.d/mongod start
  - npm install